#!/usr/bin/env bash
# Configures localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Backup original hosts file
cp /etc/hosts /etc/hosts.bak

# Configure localhost to 127.0.0.2
sed -i 's/^127.0.0.1.*localhost/127.0.0.2\tlocalhost/g' /etc/hosts

# Add facebook.com to resolve to 8.8.8.8
echo "8.8.8.8    facebook.com" >> /etc/hosts
